<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1SLI36j' shared service.

return $this->privates['.service_locator.1SLI36j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'party' => ['privates', '.errored..service_locator.1SLI36j.App\\Entity\\Party', NULL, 'Cannot autowire service ".service_locator.1SLI36j": it references class "App\\Entity\\Party" but no such service exists.'],
], [
    'party' => 'App\\Entity\\Party',
]);
