<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mt2igq5' shared service.

return $this->privates['.service_locator.mt2igq5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartyController::delete' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PartyController::edit' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PartyController::index' => ['privates', '.service_locator.8Z7eWdK', 'get_ServiceLocator_8Z7eWdKService.php', true],
    'App\\Controller\\PartyController::show' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PersonController::delete' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
    'App\\Controller\\PersonController::edit' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
    'App\\Controller\\PersonController::index' => ['privates', '.service_locator.a3q39ST', 'get_ServiceLocator_A3q39STService.php', true],
    'App\\Controller\\PersonController::show' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
    'App\\Controller\\PartyController:delete' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PartyController:edit' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PartyController:index' => ['privates', '.service_locator.8Z7eWdK', 'get_ServiceLocator_8Z7eWdKService.php', true],
    'App\\Controller\\PartyController:show' => ['privates', '.service_locator.1SLI36j', 'get_ServiceLocator_1SLI36jService.php', true],
    'App\\Controller\\PersonController:delete' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
    'App\\Controller\\PersonController:edit' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
    'App\\Controller\\PersonController:index' => ['privates', '.service_locator.a3q39ST', 'get_ServiceLocator_A3q39STService.php', true],
    'App\\Controller\\PersonController:show' => ['privates', '.service_locator.wc24vR1', 'get_ServiceLocator_Wc24vR1Service.php', true],
], [
    'App\\Controller\\PartyController::delete' => '?',
    'App\\Controller\\PartyController::edit' => '?',
    'App\\Controller\\PartyController::index' => '?',
    'App\\Controller\\PartyController::show' => '?',
    'App\\Controller\\PersonController::delete' => '?',
    'App\\Controller\\PersonController::edit' => '?',
    'App\\Controller\\PersonController::index' => '?',
    'App\\Controller\\PersonController::show' => '?',
    'App\\Controller\\PartyController:delete' => '?',
    'App\\Controller\\PartyController:edit' => '?',
    'App\\Controller\\PartyController:index' => '?',
    'App\\Controller\\PartyController:show' => '?',
    'App\\Controller\\PersonController:delete' => '?',
    'App\\Controller\\PersonController:edit' => '?',
    'App\\Controller\\PersonController:index' => '?',
    'App\\Controller\\PersonController:show' => '?',
]);
