<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.translation_debug' shared service.

$this->privates['console.command.translation_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand(($this->services['translator'] ?? $this->getTranslatorService()), ($this->privates['translation.reader'] ?? $this->load('getTranslation_ReaderService.php')), ($this->privates['translation.extractor'] ?? $this->load('getTranslation_ExtractorService.php')), 'C:\\backup_booze/translations', 'C:\\backup_booze/templates', [0 => 'C:\\backup_booze\\vendor\\symfony\\validator/Resources/translations', 1 => 'C:\\backup_booze\\vendor\\symfony\\form/Resources/translations', 2 => 'C:\\backup_booze\\vendor\\symfony\\security-core/Resources/translations'], [0 => 'C:\\backup_booze\\vendor\\symfony\\twig-bridge/Resources/views/Form', 1 => 'C:\\backup_booze\\vendor\\symfony\\framework-bundle\\Command\\TranslationDebugCommand.php', 2 => 'C:\\backup_booze\\vendor\\symfony\\form\\Extension\\Core\\Type\\FileType.php', 3 => 'C:\\backup_booze\\vendor\\symfony\\form\\Extension\\Core\\Type\\TransformationFailureExtension.php', 4 => 'C:\\backup_booze\\vendor\\symfony\\form\\Extension\\Validator\\Type\\UploadValidatorExtension.php', 5 => 'C:\\backup_booze\\vendor\\symfony\\form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension.php', 6 => 'C:\\backup_booze\\vendor\\symfony\\validator\\Util\\LegacyTranslatorProxy.php', 7 => 'C:\\backup_booze\\vendor\\symfony\\framework-bundle\\CacheWarmer\\TranslationsCacheWarmer.php', 8 => 'C:\\backup_booze\\vendor\\symfony\\translation\\DataCollector\\TranslationDataCollector.php', 9 => 'C:\\backup_booze\\vendor\\symfony\\twig-bridge\\Extension\\TranslationExtension.php']);

$instance->setName('debug:translation');

return $instance;
