<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.1SLI36j.App\Entity\Party' shared service.

return $this->privates['.errored..service_locator.1SLI36j.App\\Entity\\Party'] = new \App\Entity\Party();
