<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\PersonType' shared autowired service.

return $this->privates['App\\Form\\PersonType'] = new \App\Form\PersonType();
