<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYU4dU1B\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYU4dU1B/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYU4dU1B.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYU4dU1B\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYU4dU1B\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YU4dU1B',
    'container.build_id' => 'fa7e25a4',
    'container.build_time' => 1562334103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYU4dU1B');
