<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'bill_index' => [[], ['_controller' => 'App\\Controller\\BillController::index'], [], [['text', '/bill/']], [], []],
    'bill_new' => [[], ['_controller' => 'App\\Controller\\BillController::new'], [], [['text', '/bill/new']], [], []],
    'bill_show' => [['id'], ['_controller' => 'App\\Controller\\BillController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/bill']], [], []],
    'bill_edit' => [['id'], ['_controller' => 'App\\Controller\\BillController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/bill']], [], []],
    'bill_delete' => [['id'], ['_controller' => 'App\\Controller\\BillController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/bill']], [], []],
    'default' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'party_index' => [[], ['_controller' => 'App\\Controller\\PartyController::index'], [], [['text', '/party/']], [], []],
    'party_new' => [[], ['_controller' => 'App\\Controller\\PartyController::new'], [], [['text', '/party/new']], [], []],
    'party_show' => [['id'], ['_controller' => 'App\\Controller\\PartyController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/party']], [], []],
    'party_edit' => [['id'], ['_controller' => 'App\\Controller\\PartyController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/party']], [], []],
    'party_delete' => [['id'], ['_controller' => 'App\\Controller\\PartyController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/party']], [], []],
    'person_index' => [[], ['_controller' => 'App\\Controller\\PersonController::index'], [], [['text', '/person/']], [], []],
    'person_new' => [[], ['_controller' => 'App\\Controller\\PersonController::new'], [], [['text', '/person/new']], [], []],
    'person_show' => [['id'], ['_controller' => 'App\\Controller\\PersonController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/person']], [], []],
    'person_edit' => [['id'], ['_controller' => 'App\\Controller\\PersonController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/person']], [], []],
    'person_delete' => [['id'], ['_controller' => 'App\\Controller\\PersonController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/person']], [], []],
];
